# Generated by Django 3.2.13 on 2022-04-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('funcionarios', '0004_auto_20220428_0813'),
        ('empresas', '0001_initial'),
        ('produtos', '0003_auto_20220428_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número da Mesa', max_length=3)),
                ('disponivel', models.BooleanField(default=True, help_text='Indica se a mesa está disponível para novos pedidos')),
                ('cliente', models.ForeignKey(default='Anônimo', help_text='cliente sendo atendido na mesa', on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
            ],
            options={
                'ordering': ['cliente', 'numero', 'disponivel'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aberto', models.BooleanField(default=True, help_text='Indica se a comanda está aberta ou fechada')),
                ('fechado_as', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
                ('funcionario', models.ForeignKey(help_text='Funcionário que atende a mesa', on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario')),
                ('mesa', models.ForeignKey(help_text='Número da mesa sendo atendida', on_delete=django.db.models.deletion.PROTECT, to='pedidos.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitado_as', models.DateTimeField(auto_created=True, help_text='Hora que foi feito o pedido na comando')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('produto', models.ForeignKey(help_text='Produto sendo pedido', on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
        ),
    ]
