# Generated by Django 3.2.13 on 2022-04-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('produtos', '0003_auto_20220428_1145'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PedidoItens',
            new_name='PedidoItem',
        ),
    ]
