# Generated by Django 3.2.13 on 2022-04-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20220428_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.CharField(default='Avulso 01', help_text='Número da Mesa', max_length=10),
        ),
    ]
