# Generated by Django 3.2.13 on 2022-04-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_mesa_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={'ordering': ['solicitado_as']},
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade pedida', max_length=10),
        ),
    ]
