# Generated by Django 3.2.13 on 2022-04-28 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do Produto', max_length=50)),
                ('disponivel', models.BooleanField(default=True, help_text='Tem produto no estoque?')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do Produto', max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Categoria', max_length=50)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.empresa')),
            ],
            options={
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
    ]
