# Generated by Django 3.2.13 on 2022-04-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produtos'),
        ),
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(default=' ', max_length=200),
        ),
    ]
